### ISSUE TITLE
Service crash, lag

### ISSUE THREAD

**Issue by crazybee0909** [marverenic/Jockey#19] opened 2015-07-09 18:40 UTC
Every time I open the app in kitkat and jellybean, it reports a crash and the service notification disappears. later, when clicked on a song, nothing happens but after sometime, the app starts playing. Please fix the service issue

**Comment by marverenic** [comment] 2015-07-10 03:15
I think I know why there's a delay between the service reacting to commands, but it shouldn't be noticeable on newer devices. I'll certainly look into it, but since it's based on how the processes communicate, it won't come out until the next major release.

As for the service crashing problem, I've only had one service crash reported on Crashlytics from an Alcatel OneTouch POP C5 on July 1st which was caused by a skip command. Let me know if this sounds like your device, otherwise I'll need some more information about your phone and your music library. You can also try to clear the app data or reinstall to see if that changes anything.

**Comment by crazybee0909** [comment] 2015-07-10 12:23
I tried it on a Xiaomi Redmi note running 4.4.4. Also, when debugging through studio, the service crash on startup didn't show on the logs. Maybe that's why it didn't show up on crashlytics as well. Redmi note is by no way an old device and 4.4.4 not a very old version. Please look into it

**Comment by marverenic** [comment] 2015-07-10 17:22
Jockey runs in two processes, so make sure you're looking at the right one. There's a drop down menu on the Android logcat tab that looks like this:
![debug-process](https://cloud.githubusercontent.com/assets/10948413/8624386/849d89c8-2705-11e5-9a76-184f9d87b169.png)
and you want to choose the one that ends with ":player". I've also found that the log gets cleared if you dismiss the "Jockey has stopped working" message.

Also, I recently committed a few changes to how Jockey implements Crashlytics, but it shouldn't affect logging on the remote service. The most notable change is that my API key is no longer published.

**Comment by marverenic** [comment] 2016-05-21 17:07
I'm closing this issue due to inactivity and the fact that the player service has undergone changes that may have made this issue invalid. If it is still a problem, however, feel free to create a new issue or reply to this one to have it reopened.

**Closed by marverenic** 2016-05-21 17:07 UTC
Labels: bug
