### ISSUE TITLE
Various Bugs Found, Please Fix ASAP

### ISSUE THREAD

**Issue by maysleazy** [marverenic/Jockey#4] opened 2015-03-29 16:07 UTC
* Creating a Blank Playlist from "Playlist" Tab and then creating a playlist with the same name through the song, makes the app to crash
* While Changing Music and returning to the song screen, previous song info is shown.
* Last.Fm Information about artists is only half shown, cannot click on it.
* Sometimes the seek bar in now playing screen does not move, and if moved forcefully, returns to its original position (Temporary Workaround - Go back and come to the Now Playing Screen)
* App Installs on OS 4.4 and above, but crashes on the start for KitKat.
* Cannot enter playlist name sometimes while creating playlist from album screen.
* Some UI Glitches
* Make Yellow and Orange Skin distinct, both look orange-ish.
* Improve Last.Fm Integration
* Make the Repeat icon more visible for darker album artwork.
Thanks for the awesome app though.

**Comment by marverenic** [comment] 2015-03-29 22:17
Thanks for your input. I've fixed the "create playlist from queue" option when entering a playlist name that already exists, and I've also changed yellow colors to match the yellow palette from the Material Design color page (it was previously amber) -- those will show up in the next release along with Jockey handling "open with" intents.

I've also fixed the progress bar being always filled when opening the now playing page while the current song is paused, but I'm not sure that's exactly what you meant. This will also be in the next release.

Both of my test devices run Lollipop, so unfortunately I can only check for issues on 4.0-4.4 in an emulator. Right now, the latest build (not currently on github) starts fine in the emulator, so if you can run a debug version and provide the logcat crash report, that would be really helpful. I think the easiest way to do that would be to build and run Jockey from Android Studio -- there are a lot of tutorials to import projects online, and the log file is easily visible in the "Android" tab. You'll also have to enable USB debugging on your phone. If you want I can also send you a compiled debug build, but you'll have to use ADB to get the logcat file.

I haven't experienced your second bullet point, so if you can provide steps to reproduce it and device information, that would help a lot.

At the moment, I haven't implemented creating new playlists from the "add to playlist..." option, so I'm not quite sure what you mean in bullet point 6. I also haven't thought about Last.fm integration too much, but I can certainly add it to the list of things to do if you have some specific ideas in mind.

I haven't experienced your last comment about the repeat icon being hard to see, especially on dark artwork. It should always be white, but in its off state a bit more transparent. It might help to send a screenshot, though, and it's very possible that I messed up its icon.

Sorry for that wall of text, but thanks again for your input and I look forward to any more info you can provide.

**Comment by maysleazy** [comment] 2015-03-30 08:56
For the second point, As You see, the music Playing is "Imagine Dragons - Monster" but the play screen at the bottom shows previous played song "Skrillex - Ruffnek"
![Multi Music Bug](https://cloud.githubusercontent.com/assets/11243138/6893176/67278672-d6e8-11e4-8eff-f4de277ab2f3.png)

**Comment by maysleazy** [comment] 2015-03-30 08:57
Also, can you add a cross (x) button to the notification play area?

**Comment by marverenic** [comment] 2015-03-30 20:37
I found the problem with the miniplayer not updating after you leave the page, so that will go out with the rest of the patches. With your last comment, if you're referring to closing the notification then I'm planning to implement that in the next release. The current plan is to keep the player service running after Jockey is removed from the recent apps page, and then stop the service by pausing the song and dismissing the notification (Which is pretty much what Google Play Music currently does).

**Comment by maysleazy** [comment] 2015-03-31 02:00
That's it for now, I'll update if I find any more bugs. Thanks :)

**Comment by maysleazy** [comment] 2015-03-31 17:55
Another Issue is a major one.
The application installs on KitKat, but doesn't work, crashes on start.
Tested with various devices running KitKat.

**Comment by marverenic** [comment] 2015-03-31 21:31
I still haven't been able to reproduce the startup crash in an Android 4.4.2 emulator. Can you be more specific about what devices (e.g. AT&T Samsung Galaxy S4 or Verizon Moto X 2014) and which version (e.g. 4.4.2 or 4.4.4) you experience this on? Any other information about when or how it crashes would also help a lot (e.g. the action bar appears briefly before crashing, or Jockey crashes before any of its UI is shown).

Information about the device's setup is also important, so please provide as much as you can. Any information about its storage, locale, network status, and background apps can affect Jockey (e.g. it doesn't have a SIM card, Jockey is on an SD card, your music is on an SD card, its language isn't English, it uses a right to left layout, it doesn't run Google Play Services, the device doesn't have any music, the device has a lot of music, etc.)

It would also help greatly if you could figure out which version of Jockey was the last version that successfully started on your devices (In order to install an older version from SourceForge you'll have to remove the newer version first).

In the meantime, you can try clearing Jockey's data and redownloading and installing the latest version from SourceForge to see if that helps at all.

**Comment by maysleazy** [comment] 2015-04-01 12:54
Every KitKat phone that I've tested...

**Comment by marverenic** [comment] 2015-04-02 03:20
Every device I've tested has been unable to reproduce this crash. Below is a list of the devices that I've tested this on, sorted by software version:
- HTC Nexus 9 (5.0.1)
- Verizon Moto X 2nd generation (5.0.0)
- Verizon Samsung Galaxy Note 3 (4.4.4)
- GSM Samsung Galaxy S4 (4.3.0)

I'll attempt to push a new build tomorrow or Friday with the patches from before and more extensive logging to help diagnose this, but the "open with Jockey" action and background player service won't be included since they're still pretty broken.

**Comment by maysleazy** [comment] 2015-04-02 17:57
I'll give it a try when you update then. thanks :) :+1:

**Comment by marverenic** [comment] 2015-04-02 22:11
Jockey 0.2-α.r0m18k has just been pushed to SourceForge and Github, and you can download it directly from [this link]. Its full changelog can be found [here].

If Jockey still crashes on KitKat devices, please send its log file either in this thread or email it to marverenic@gmail.com. If you use a file explorer, you should be able to find Jockey's log file in "/sdcard/Android/data/com.marverenic.music/files/jockey.log" (/sdcard/ is also a shortcut to /storage/emulated/0). If you browse your phone's storage from Windows with your phone mounted with MTP, you should be able to find it in "Computer\[model number]\Internal Storage\Android\data\com.marverenic.music\files\jockey.log" or similar.

Jockey's log includes anonymous device information including model number, android version, memory information, locale, and network status (type and status only, no network names are ever saved). In the future if you want to report a crash, there is a menu option in the settings page under "General" called "send bug report" which will automatically compose an email to marverenic@gmail.com and attach the log file (Although unfortunately Jockey has to be able to start to use this)

[here]:https://github.com/marverenic/Jockey/commit/4436728e98a4760dcd4aeeaf13fbef429a839bf1
[this link]:https://sourceforge.net/projects/jockey-player/files/latest/download

**Comment by maysleazy** [comment] 2015-04-03 04:46
cool, will test and report asap :D

**Comment by maysleazy** [comment] 2015-04-03 09:42
Works now, thanks :)

**Comment by marverenic** [comment] 2015-04-03 20:58
I'm marking this thread as closed in response to the bug fixes. I've made another bug report (#6) for the last.fm feature request.

**Closed by marverenic** 2015-04-03 20:58 UTC
