### ISSUE TITLE
All songs show up in each album

### ISSUE THREAD

**Issue by Recordeer** [marverenic/Jockey#313] opened 2017-09-21 04:03 UTC
Every album I open shows all the songs on my sd card instead of the songs on each album.

**Comment by Recordeer** [comment] 2017-09-21 04:07
Besides that, everything else works good for me and I like the app. Good job.

**Comment by Recordeer** [comment] 2017-09-21 04:11
Oh! Also I organize my music as folders on my sd as Music/Artist/Album(sometimes)/Songs in that album. Perhaps that is why it is doing this but I am unsure.

**Comment by marverenic** [comment] 2017-09-23 01:10
Hm... I'm not sure what would be causing this. If you don't mind, can you let me know what device and version of Android you're running? Also, is this an issue that you experience in other apps?

**Comment by Recordeer** [comment] 2017-09-30 06:54
The Device is 4.4.4 I believe and no on google play (the only other music player I use) it does not do this. (I like this app better though as it shows the album art better)

**Comment by Recordeer** [comment] 2017-09-30 06:56
It is an Alcatel Onetouch and version 4.4.4

**Comment by marverenic** [comment] 2017-09-30 15:56
Thanks for the info. Unfortunately, I'm unable to reproduce this in an Android 4.4.4 emulator with music stored on an SD card in a similar folder structure.

You may be able to fix this by ensuring that your music is correctly tagged and sorting it into album folders. Additionally, you can also try to force Android to rescan your SD card's music. This normally happens when you reboot your phone or reinsert the SD card, but there are also a couple of apps on the Play Store that can perform this rescan. 

If you want a more nuclear option for rescanning your SD card, you can open settings, navigate to apps, locate "Media Storage" (under all apps), clear its data, and then reboot your phone. Note that you'll need to reset any custom notification or ringtone settings you've changed, and I strongly advise against doing this.

**Comment by Recordeer** [comment] 2017-10-03 22:50
I found resetting the app data solved the problem.  ¯\_(ツ)_/¯ I also only encounter the problem when I change the app colors. So ya problem solved I guess. I didn't need to reboot after resetting either.

**Comment by marverenic** [comment] 2017-10-04 00:19
Huh. That's really weird. I'm going to go ahead and close this for now since you've gotten it resolved, but let me know if you're able to reproduce it in the future.

**Closed by marverenic** 2017-10-04 00:19 UTC
Labels: bug, cannot reproduce
