### ISSUE TITLE
Nullpointer exception occured

### ISSUE THREAD

**Issue by androrz** [marverenic/Jockey#31] opened 2015-11-19 01:17 UTC
11-19 09:14:25.681: E/AndroidRuntime(15017): FATAL EXCEPTION: main
11-19 09:14:25.681: E/AndroidRuntime(15017): Process: com.marverenic.music, PID: 15017
11-19 09:14:25.681: E/AndroidRuntime(15017): java.lang.NullPointerException
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.os.Parcel.readException(Parcel.java:1471)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.os.Parcel.readException(Parcel.java:1419)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at com.marverenic.music.c.b(IPlayerService.java:300)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at com.marverenic.music.PlayerController.b(PlayerController.java:91)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at com.marverenic.music.activity.a.onClick(BaseActivity.java:276)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at com.marverenic.music.activity.LibraryActivity.onClick(LibraryActivity.java:126)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.view.View.performClick(View.java:4463)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.view.View$PerformClick.run(View.java:18772)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.os.Handler.handleCallback(Handler.java:808)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.os.Handler.dispatchMessage(Handler.java:103)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.os.Looper.loop(Looper.java:193)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at android.app.ActivityThread.main(ActivityThread.java:5367)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
11-19 09:14:25.681: E/AndroidRuntime(15017): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by marverenic** [comment] 2015-11-19 02:19
I found one way to cause this crash is to press the skip button when nothing is playing, but I can't really tell if that's what caused this crash since the exception was thrown in the player process. Can you provide steps to reproduce this?

**Comment by androrz** [comment] 2015-11-19 03:00
@marverenic press the skip button when nothing is playing will cause this problem

**Comment by marverenic** [comment] 2015-11-19 03:03
Thanks. This should be fixed as of commit 9557486 and will roll out in 1.1.1 beta 1

**Closed by marverenic** 2015-11-19 03:03 UTC
Labels: bug
