### ISSUE TITLE
Log for crash + one bug +One Enhancement request

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#7] opened 2015-04-09 13:17 UTC
+ Found this crash while clicking on any artists in the "Artist" tab. To emulate this crash, run the app on CyanogenMod ROM or any other AOSP ROM.

``` 
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
	at java.util.ArrayList.get(ArrayList.java:304)
	at com.marverenic.music.e.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:856)

```

+ Status bar bug - While playing a song in shuffle mode, when a song finishes, the next song isn't updated in the status bar, fix it pls.

+ Enhancement
Please add "keep the application in service" even after it is removed from recent apps screen

**Comment by marverenic** [comment] 2015-04-09 20:09
I think I've found the cause of the crash (it was a terrible and unnecessary hack that assumed your artists always had at least one album), so that should be fixed in the next update.

I ran into the bug where the notification wouldn't update and I think I've already fixed it, but I've had to overhaul a lot of the player service again so that it can run properly in the background like you mention in your third point, so I'm sure other new and exciting bugs will magically appear as usual.

**Comment by maysleazy** [comment] 2015-04-10 07:12
LOL, I'll be working on it too, I got it in service, but the mNotification Builder doesn't want to work it seems, tried making custom notification for the X mark to close in the notification, idk why but it just doesn't go off. Waiting for your build to come to check what I've missed, would be fun if I stand corrected.

Also, the artist description is mostly half given and clicking on it doesn't reveal the full info, can you please make it a click on because people tend to read artist bios.

waiting for the new build :)

**Closed** 2015-06-25 03:08 UTC
