### ISSUE TITLE
Small features that can go a long way

### ISSUE THREAD

**Issue by orominioo** [marverenic/Jockey#37] opened 2016-02-14 16:20 UTC
Has I previously stated I love the simplicity of the App, in my Nexus 5 it runs perfect, but theres a few features that can add a lot of potential to the player here ara a few:

- Share option. It will be nice to share the song with any app (Mainly on whats app).

-Repeat 3. I love to repeat song but it gets annoying after a couple of repeats, I use the app mainly on the car so its not wise to use the phone while driving, a option to set the song on repeat only 3 times and the go to the next song and play the rest normal (one time). 

-Background Play. Has I stated before I use the app moustly on my car, if a want to record a Whatsapp voice the song stop, it will be nice if instead it just volume down a little and after the voice finish recording 
gradually increase the volume back.

- Play and Pause Gradually. when the song is pause and play after pause will be nice if it gradually increase volume until back at the right volume instead of just play at the volume it was.

-Soundcloud Integration. It will be perfect if a can be able to play at least my Liked song from Soundcloud.

-Recently Added TAB - Not a playlist just a tab with the recent songs. (Simple but useful).

-Playlist algorithm - I havent manage to do this on the smart playlist but it will be nice if a "Radio" features could be include, it will be like a playlist that will go with this algorithm: Play 1 recent added song, 2 most played song, 2 random song(Not recent, not most played). then start again, that way its easier to listen  all the songs.
a = recent song
b = most played song
c = random song(Not recent, not most played)
it will go like  b,a,b,c,c,b,a,b,c,c,... and so on.

-WhatsApp voice - PLEASE! add the option so the player skips whatsapp voice, if the audio file starts with "AUD-'somedate'-WA####" dont include it to the library. 

-Bluetooth and AUX - I dont know if this is posible but, it will be Perfect if a can play music trough the AUX while im in a call on the bluetooth.

My car have a sound System and does details will go a long way and could easily make the app a lot smoother.

**Comment by marverenic** [comment] 2016-02-15 00:06
Sharing wouldn't be too hard to implement, but are you interested in sharing song information, the actual song itself, or would you prefer to have the option to choose between both?

The WhatsApp filenames seem a bit specific, but would a simple directory inclusion/exclusion setting work? There's definitely going to be times where Android claims audio files are music, and I'd much rather leave it in the hands of users to decide for their needs. It's also much faster to tell if a filename starts with a string rather than to see if any substring matches a pattern.

I haven't thought about repeat 3 before -- especially because I haven't seen a music player with that option. It wouldn't be too bad to implement, but some of the player code might need to be cleaned up before it gets implemented. If I understand it correctly, only the song that's currently playing gets repeated and then the rest of the playlist is normal, right?

Fading in and out would also happen when the player code gets cleaned up. I'd like to implement it with crossfade and gapless playback, but there's a bit of MediaPlayer juggling that has to happen behind the scenes.

Soundcloud integration, the recently added page, and a radio list sound like features for a 2.0 release. I've put thought into adding network sources to Jockey, but I'm not ready to link it to more API's just yet. I can't promise anything because of my school schedule, but I would expect work on this to start closer to the beginning of Summer.

Having music play while you're recording with WhatsApp is a pretty technical thing that would cause a lot of unexpected behavior. Android has an AudioFocus pattern so that only 1 app can play music at a time. Whenever something else wants to play sound, it should request the focus from the other app. When it does this, it can either gain permanently, transiently, or transiently while allowing the current source to "duck" (which is what happens when you get a notification) -- you can read more about this [here](http://developer.android.com/training/managing-audio/audio-focus.html#HandleFocusLoss). If an app doesn't follow this pattern, then you can get two sources of music playing at the same time. The problem here is that WhatsApp is taking the AudioFocus so that it can mute everything else, and there's not a good way to detect that it's done this without a lot of weird hacks that I'd prefer to avoid.

Android normally manages all audio output on its own. I wouldn't be too surprised if it's possible to output to different sources, but it seems like something that could introduce a lot of unexpected behavior and bugs. You could try searching the Play Store to see if someone else has made an app that lets you set the output source for all your other apps, but I'm not sure how much luck you'll have.

**Comment by orominioo** [comment] 2016-02-15 23:22
1. Share. Yes Both option will be perfect, I could share the file or just share the song info (Now playing song) will be good additions.

2.Exclude Directory while be the best features, (I dont know why I didn't think that). This will kill all potential future unwanted audio files to be read by the player.

3. Repeat 3 Yes you understand it perfectly!

I understand that the other stuff are not so important but you can put them on a TODO just in case in the future want to try and implement them. Though the "Radio"(I call it the radio algorithm because radio stations have a specific way of playing songs, they do not play them randomly, you can call it whatever you want) algorithm will open a lot of door for the app, you can great a income from the app without even showing ads! but thats another talk for another day. If you want to try to implement a algorithm like that I can help you no problem.

Overall those 4 can easily be perfect additions, number 3 specifically.
Those recommendations are all based on User Experience and thats what make a App standout.

**Comment by marverenic** [comment] 2016-07-01 01:42
Directory inclusion/exclusion has been added to `master` with #69. It will be released in the next version of Jockey.

I've created a couple of separate issues for some of your other points. See:
 - #66: Add a page specifically for recently added songs
 - #67: Add an option to crossfade when playing and pausing songs
 - #68: Add an option to enable Multirepeat

I've made a note of your requests for a "Radio" playlist and Soundcloud integration, but I believe that there are other feature requests that will be more valuable and easier to integrate in the meantime.

Feel free to submit new issues for these, but because it's hard to keep track of large issues like this one, I'm going to close this issue in favor of the separate issues.

**Closed by marverenic** 2016-07-01 01:42 UTC
Labels: enhancement
