### ISSUE TITLE
Pause and skip song with headset click

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#44] opened 2016-04-18 07:46 UTC
A minor suggestion that's useful for many - pause the song on single click on headset button and skip to next song on double click.

PS : I think the reason why Media action button listeners are not working properly on some device is because you haven't set a priority for RemoteControlReceiver in the manifest.

**Comment by marverenic** [comment] 2016-05-12 02:05
Sorry I took so long to get back to you -- I've been pretty busy with the semester ending last week.

Single clicking the headset remote button currently does toggle between play/pause on my Moto X 2nd generation and Nexus 9 running 5.1 and the N developer preview respectively, and I'm not sure why it wouldn't be working on your device. I recently found that Jockey doesn't properly capture media focus on its first launch when a song is played for the first time, but it shouldn't affect you since it's resolved after pausing playback or restarting Jockey.

`RemoteControlReceiver` actually isn't even being used anymore -- [`MediaSessionCompat`](http://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.html) with a [`MediaSessionCompat.Callback`](http://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.Callback.html) is being used to handle play/pause key events.

Double and triple clicks to skip would be nice to implement, but I'm not sure what the best way to go about doing this is, since the callback that handles play/pause events from headset remotes also handles play/pause events from other sources (like keyboards).

**Comment by salvator91** [comment] 2016-05-14 03:23
What about using KeyEvent.KEYCODE_HEADSETHOOK ? 

I see you have omitted RemoteControlReceiver completely. Won't it affect playback?

**Comment by marverenic** [comment] 2016-05-15 22:21
I've looked into `MediaSessionCompat` a bit more, and I've come to the following conclusions:
- `RemoteControlReceiver` was being used, but only on devices running API 19 and lower (which I hadn't tested before removing it). As of right now, the service crashes when it starts on pre-Lollipop devices, because `MediaSessionCompat` throws an `IllegalStateException` when it can't find a BroadcastReceiver that handles `android.intent.action.MEDIA_BUTTON` actions.
- Android only allows one BroadcastReceiver for media buttons to be active (because pressing the play button on 10 media players would be very bad). It determines which receiver to send the broadcast to based on when it was registered, favoring the most recently added. Since `MediaSessionCompat` creates this receiver automatically on Lollipop and up using the `MediaSessionCompat.Callback` implementation, the solution you linked to wouldn't apply on API 21+.
- Jockey's current use of `MediaSessionCompat` isn't as complete as it could be, and doesn't take advantage of a lot of extra functionality and free boilerplate code in the support libraries.

I'm working on addressing these points, but they're all intertwined to an extent and affect the service notification a bit, so it's probably going to roll into a somewhat large commit.

I'm not quite sure where `KeyEvent.KEYCODE_HEADSETHOOK` fits into this, because Android appears to treat it the same as `KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE` -- and from the tests I was able to perform, the latter is the event sent from inline remotes. From what I've seen, though, the link you posted is how several others have accomplished this before the APIs added in Android 5.0.

**Comment by marverenic** [comment] 2016-05-21 19:28
I've created the branch [m/media-session-compat](https://github.com/marverenic/Jockey/tree/m/media-session-compat) to be able to work on the MediaSessionCompat implementation without affecting master. It should fix the crash on API 19 introduced in 28c655a, but it introduces a few problems of its own. Most notably, a0f50ea started the migration of the service notification to use NotificationCompat.MediaStyle, which has temporarily broken the ability to stop the service.

**Comment by salvator91** [comment] 2016-06-02 10:23
If u are still working on this app..Here's an implementation of headset click that you can have a look into
It seems you ave only implemented ACTION_UP and not ACTION_DOWN

https://github.com/CyanogenMod/android_packages_apps_Eleven/blob/cm-12.0/src/com/cyanogenmod/eleven/MediaButtonIntentReceiver.java

**Comment by marverenic** [comment] 2016-06-03 02:25
Don't worry -- I'm still working on Jockey, but I have a summer internship doing Android app development which doesn't give me as much free time as I had before, so most of the commits to Jockey will happen on weekends. The internship has also introduced me to a lot of libraries and patterns that I hope to implement in Jockey eventually, starting with in [m/dagger](https://github.com/marverenic/Jockey/tree/m/dagger) branch, which sets up Dependency Injection and RxJava to make the in-memory music library easier to work with and simplify a lot of UI logic. In addition, I'm also moving new features into their own branch until the implementation is complete, which you've probably noticed.

With regards to `ACTION_DOWN`, I don't think that there's anything to implement. Each button press triggers an event when the button is both pressed and released (corresponding to `ACTION_DOWN` and `ACTION_UP` respectively). I believe that specifying behavior for `ACTION_DOWN` would just double-count each event.

The main thing that's left to do on [m/media-session-compat](https://github.com/marverenic/Jockey/tree/m/media-session-compat) is to implement killing the service on API 21 and higher by swiping away the notification. This will leave double and triple click behavior undefined, but I don't think that this can easily be done with the newer APIs.

**Comment by salvator91** [comment] 2016-06-05 18:47
I guess they are checking the number of clicks or the duration between clicks to determine a double click and skip to next song or triple click to switch to previous song. That's the reason for having a separate block for ACTION_DOWN.

**Comment by shkschneider** [comment] 2016-06-13 15:38
CyanogenMod uses a frameworks_base patch to dispatch those media events to the system upon long-press of volume-up or down (it simulates a previous/next), which often called "Volume Rocker" in their changelogs. This feature is not something that could come from the application itself I'm afraid.

**Comment by salvator91** [comment] 2016-06-22 13:11
Can you make something out of this?
http://stackoverflow.com/questions/30942054/media-session-compat-not-showing-lockscreen-controls-on-pre-lollipop

**Comment by marverenic** [comment] 2016-06-23 03:45
:+1: Good link @salvator91. I didn't realize that `MediaSessionCompat.Callback` had an `onMediaButtonEvent(Intent)` method -- I thought it was all abstracted away by the support library.

I've only tested this on a phone with 5.1.1, but the following code appears to do the right thing:
```
@Override
public boolean onMediaButtonEvent(Intent mediaButtonEvent) {
    KeyEvent keyEvent = mediaButtonEvent.getParcelableExtra(Intent.EXTRA_KEY_EVENT);
    if (keyEvent.getKeyCode() == KeyEvent.KEYCODE_HEADSETHOOK) {
        Log.i(TAG, "Headset button pressed");
        // TODO: Count clicks and post delayed runnable
        return true;
    } else {
        return super.onMediaButtonEvent(mediaButtonEvent);
    }
}
```

**Comment by marverenic** [comment] 2016-06-23 04:14
Just uploaded a commit to [m/remote-actions](https://github.com/marverenic/Jockey/tree/m/remote-actions) that should implement this. Let me know if it's working as you'd expect.

**Comment by salvator91** [comment] 2016-06-23 11:55
Great. Does this work on API < 21 ? I have an API 19 device to test. Hope it does work

**Comment by salvator91** [comment] 2016-06-23 17:51
Actually this isn't working. Playback itself has stopped for some reason. I am testing on API 19. Why have you done away with all the BroadcastReceivers in Playerservice?

**Comment by marverenic** [comment] 2016-06-24 03:16
Can you be more descriptive about what's not working? I just tested this in an API 19 emulator and it appears to be working as intended.

The reason that the broadcast receivers were removed, by the way, is because they weren't needed. MediaSessionCompat includes a lot of this implementation for free, which is why I switched to it. The one thing that isn't handled by MediaSessionCompat, however, is headphone disconnects, which are still responded to with a BroadcastReceiver in `MusicPlayer`.

On API 21+, MediaSessionCompat can directly register our `MediaSessionCompat.Callback` with the system, forgoing BroadcastReceivers all together. On API 19 and below, Jockey's Android Manifest specifies `android.support.v4.media.session.MediaButtonReceiver` as a BroadcastReceiver for `android.intent.action.MEDIA_BUTTON` actions. The support library's implementation looks for services with the same intent filter, and forwards Intents along to the service's `onStartCommand()` method. When we get this Intent, we actually just pass it right back into MediaSessionCompat by calling `MediaButtonReceiver.handleIntent()`, which figures out which method in our `MediaSessionCompat.Callback` to use for the KeyEvent that just happened, and fires it back to us to handle the event. The result of this is that we don't have to do anything with BroadcastReceivers ourselves to handle media Intents -- the support library takes care of all of it -- hence the lack of BroadcastReceivers in `PlayerService`. If you're interested, Ian Lake gave a [presentation about MediaSessionCompat](https://youtu.be/XQwe30cZffg) where he actually talks about this around [14:30](https://youtu.be/XQwe30cZffg?t=14m30s)

**Comment by marverenic** [comment] 2016-06-25 20:53
I've gone ahead and merged this from `m/remote-actions` into `master` with 05170f4. If there are other issues related to playback, please feel free to start a new issue.

**Closed by marverenic** 2016-06-25 20:53 UTC
Labels: bug, enhancement
