### ISSUE TITLE
Refresh library not working

### ISSUE THREAD

**Issue by AKprisonER** [marverenic/Jockey#234] opened 2017-03-02 15:55 UTC
i compared app from playstore and app generated from this build .
Even after granting storage permissions,no media is displayed in app that was generated from this build.
I think this is due to your last update on Media Util file

**Comment by marverenic** [comment] 2017-03-02 16:09
Thanks for pointing this out -- I was able to reproduce this on a Marshmallow emulator, but this does behave correctly on Nougat 7.1. I'll look into this soon, but I think you're right that 4e10086 is causing this.

**Comment by marverenic** [comment] 2017-03-02 16:24
Whoops, I was testing the `demo` flavor instead of `standard`. I am unable to reproduce this bug. Please provide reproduction steps as well as the device and version of Android you're using. Also make sure that you're building one of the `standard` flavors in Android Studio.

**Comment by AKprisonER** [comment] 2017-03-02 19:41
i tried building variant "standardDebug" and "Standard release-by removing crashlytics".After several trial and error ,succesfully built.I was testing all the generated files in REDMI/Mi phones.As the have several complications over their MiUi,Jockey app is unstable in nearly 3 out of 5 Mi phones.So i recommend others to use physical device other than Mi.
If you want to work with that bug,you can head over/add  fragment 

int permissionCheck = ContextCompat.checkSelfPermission(getActivity(),
            Manifest.permission.READ_EXTERNAL_STORAGE);
 u have to over come this by adding this to manifest files.
           if (ContextCompat.checkSelfPermission(context, Manifest.permission.READ_CONTACTS)
                == PackageManager.PERMISSION_DENIED)
            ActivityCompat.requestPermissions(this,
                    new String[]{Manifest.permission.READ_CONTACTS},
                    PERMISSION_REQUEST_CODE)
Apks are working fine in all other models except redmi miui8 MM,MiUi 7 KK.

**Comment by marverenic** [comment] 2017-03-03 04:28
Unfortunately, I don't have access to a device capable of running MiUi 7 or 8 since Xiaomi is not a very common brand in the US. Please open a PR if you're able to find a fix for this.

Alternatively, let me know if there's a way of testing on MiUi without a Xiaomi device – either through an emulator or with a ROM for the Google Pixel XL, Nexus 9, or Moto X XT1096.

**Comment by androrz** [comment] 2017-05-07 01:53
yes, i'am also testing demo flavor instead of  product flavor, this is not a bug

**Closed** 2017-05-18 02:11 UTC
Labels: invalid
