### ISSUE TITLE
[request] Highlight Song Name

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#136] opened 2016-10-08 21:11 UTC
Can you please highlight the Song name of the All the Fragments [Primary color]

And the current song must always be shown on the top of the RecyclerView like in the QueueFragment scroll to current.

Will be a lot easier for all the Users to Navigate  :)

Thanks

**Comment by marverenic** [comment] 2016-10-09 01:50
This is a duplicate of #103.

In response to keeping the current track at the top of the song fragment, I think this is a bad idea since songs can change without user interaction (i.e. when they're in the middle of looking for a different song) and there's not really a benefit in pinning the current song to the top of the screen.

**Closed by marverenic** 2016-10-09 01:50 UTC
Labels: duplicate, enhancement
