### ISSUE TITLE
This build has problem in listing songs to the player

### ISSUE THREAD

**Issue by AKprisonER** [marverenic/Jockey#233] opened 2017-03-01 17:37 UTC
refresh library is not working.
also JocketComponentFactory file should be placed in music/data/inject folder
You had placed it in a seperate file that creates multiple errors.
Can u plz built it from this git source?Yu can see some bugs like missing of auto refresh,etc.,

**Comment by marverenic** [comment] 2017-03-02 16:19
The version of Jockey that I build is the exact same one that's on GitHub. `JockeyComponentFactory` is in the correct directory (since a different class is used in the `standard` and `demo` flavors). I was able to successfully clone the repo and open it in Android Studio with no compilation errors. Additionally, Travis CI guarantees that `master` will always compile from Gradle (otherwise a commit will be blocked from `master`).

Jockey has never had auto-refresh (so it's not a bug that it's missing). I am planning to add it soon, though.

I'm going to go ahead and close this since there's another issue #234 for the refresh bug.

**Closed by marverenic** 2017-03-02 16:19 UTC
