### ISSUE TITLE
Few major issues with playback

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#42] opened 2016-04-13 08:06 UTC
Since you have implemented gapless playback I have spotted several issues. Though I haven't tested it on other phones I have noticed the following on my device 
- It doesn't get exclusive audio focus. If I am playing another music app, it continues to play alongside the other one. Same is true for releasing focus as well. It doesn't release focus even if I play from another app. The new player plays alongside Jockey. 
- Sometimes after releasing focus, it doesn't play again at all. It freezes. And I have to start another song to make it play.

Its entirely possible that these are issues with my device as mine is an extremely faulty and cheap phone (micromax). But still I hope u look into them. Because none of these issues were present prior to gapless playback.

Another issue I would like to point is that player controller doesn't seem to receive updates from lockscreen. If I pause a song from lockscreen the play/pause button in the miniplayer and now playing activity doesn't get changed.

**Comment by marverenic** [comment] 2016-04-15 02:51
I was able to reproduce the audio focus bugs pretty easily; they should be fixed in 42115ff.

I haven't been able to reproduce activities not updating when being brought back into the foreground (Although a bug where notification buttons wouldn't cause the notification to update should be fixed in 083bd1c). If you let me know what version of Android your phone is running and any extra steps you took to reproduce this, then I'll be sure to look into it.

**Comment by marverenic** [comment] 2016-04-15 03:38
As an update to the stale activity/notification bug, I've reverted 083bd1c because the issue was being caused by another bug (which should be resolved in 940f3a5). I don't know if this will make a difference or not, but let me know if it does.

**Comment by salvator91** [comment] 2016-04-15 05:36
Actually I didn't download it from Playstore. Long time back I did, but then I had to delete apps to save space. After that when I tried to reinstall it, the playstore throws an error (code -24). So I copied your project into android studio and compiled & installed it manually. 

Anyways, the audiofocus issue is sorted, but the playpause button issue seems to be still there. I'll test it on my friend''s pone and tell you.

**Comment by salvator91** [comment] 2016-04-15 06:54
One more thing. The player doesn't automatically start playing after ending a phone call (audiofocus regain). I am guessing some rearrangement of the boolean variables assignment is in order. :-)

**Comment by marverenic** [comment] 2016-04-15 15:30
According to [a post](http://android-developers.blogspot.com/2013/08/respecting-audio-focus.html) on the Android Developers blog from a few years ago, it looks like phone calls are a bit more aggressive about audio focus. If a phone call is ongoing when AudioFocus is requested, Android will return `AUDIOFOCUS_REQUEST_FAILED`, and when a phone call ends, `AUDIOFOCUS_GAIN` isn't granted back to the last media source.

I believe that typically media players get around this by adding a BroadcastReceiver to listen for phone call ends, so I've created a new issue (#43) for this feature request since it's outside the scope of this one.

**Comment by salvator91** [comment] 2016-04-15 15:41
Ok...Just wanted to ask one more thing. In your device is the lockscreen/notification play/pause syncing well with miniplayer / nowplaying play pause buttons? Suppose I click pause from the notification view. Is that change being reflected in the now playing activity's play pause imageview or that of the mini player?

**Comment by marverenic** [comment] 2016-04-16 04:07
[Here's the behavior I'm getting when the app is in the foreground](https://gfycat.com/FrailWetKid), and [here's the behavior I get from the lock screen](https://gfycat.com/ReliableSparklingBichonfrise) using the current repository version of Jockey on my second generation Moto X.

How are you building Jockey, by the way? If you're doing a signed release, there's the possibility that proguard might be getting rid of something important that's kept in debug builds.

**Comment by marverenic** [comment] 2016-11-21 03:35
Because Jockey has switched to ExoPlayer for music playback, I'm going to close this issue. If this is still a problem, please feel free to open a new issue.

**Closed by marverenic** 2016-11-21 03:35 UTC
Labels: bug
