### ISSUE TITLE
android kitkat

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#102] opened 2016-07-26 14:17 UTC
Not working on kitkat it keeps crashing on the splash screen

**Comment by Dirkstaal** [comment] 2016-07-26 18:03
Working on android 5.1 but not on 4.4 tried on several several devices

**Comment by marverenic** [comment] 2016-07-27 01:37
I'm unable to reproduce this in a 4.4 emulator with the code in master. Please let me know what phone and version of Jockey you're running, as well as the stacktrace if possible. I checked Crashlytics and I don't see a crash that matches the description you've provided. If you've built Jockey yourself, then there's the possibility that something didn't compile correctly, so be sure to try the latest version from Google Play if you built it yourself (you can [opt-in to the beta](https://play.google.com/apps/testing/com.marverenic.music) if necessary)

There's also a possibility that this is being caused by an issue in version 24.1.0 of the Android Support Libraries, where resource ids added by support libraries could be mismatched. This has been fixed in [24.1.1](https://developer.android.com/topic/libraries/support-library/revisions.html#rev24-1-1), so it's just a matter of updating the support library versions.

**Comment by Dirkstaal** [comment] 2016-07-27 05:31
Ok thanks

**Comment by Dirkstaal** [comment] 2016-07-27 05:38
Its the master branch latest and it did work on my Lollipop not kitkat also
version 1.2 works on the kitkat but it does not show the music on the kitkat

**Comment by Dirkstaal** [comment] 2016-07-27 05:54
Ok so i just tested the 2.02 from play store on my 4.4 it works perfectly (so i should just update all the support libraries to use 24.1.1)

**Closed** 2016-07-27 23:51 UTC
Labels: bug
